### ISSUE TITLE
Prevent duplicate Complex Field group.

### ISSUE THREAD

**Issue by Santana1053** [htmlburger/carbon-fields#229] opened 2017-05-12 21:03 UTC
Using multiple groups in Complex Field, is there a way to prevent a group from being added more than once?

**Comment by atanas-angelov-dev** [comment] 2017-05-15 06:12
Hi @Santana1053 ,

Currently, this is not available as an option.

---

Marking as duplicate of #96 .

**Closed** 2017-05-15 06:12 UTC
Labels: duplicate
