### ISSUE TITLE
rich_text field auto focused on load

### ISSUE THREAD

**Issue by edwardhew** [htmlburger/carbon-fields#391] opened 2017-10-28 14:45 UTC
Hi guys,

I'm using 2.1 for the first time, is it me or does the rich_text field auto focus on page load?

`Field::make('rich_text', 'desc', 'Description')`

I closed and relaunched browser (Firefox) and the page always scrolls down to the rich_text field and the form editor has focus, cursor is in there blinking.

Thanks as always to CF team.

**Comment by atanas-angelov-dev** [comment] 2017-10-28 16:23
Hi @edwardhew ,

Rich text being "focus greedy" is a known issue that is already addressed in the latest beta. If you are feeling adventurous you can install it using `^2.1.1-beta.5` in composer.json.

Closing - duplicate of #381

**Closed by atanas-angelov-dev** 2017-10-28 16:23 UTC
