### ISSUE TITLE
Term Meta > Complex Field Always Returns Empty Array In REST API

### ISSUE THREAD

**Issue by richardbuff** [htmlburger/carbon-fields#393] opened 2017-10-30 14:36 UTC
I tested this by adding a complex field to `post_meta` container and setting `set_visible_in_rest_api` and it appears in the API response as expected. (screenshot https://cl.ly/1j0N0g3g4126 )

However, the same code when added to `term_meta` container will always return an empty array in the API response.  (screenshot: https://cl.ly/3l3X1g3e2X1Y )

Side note: its unclear from the docs if `set_visible_in_rest_api` needs to be applied to the complex field itself or to all its children fields (or both).

Here is the code I'm using to register the term meta: https://gist.github.com/richardbuff/c8df2e72f2aa439959424d80bace2271

**Comment by mathiasoem** [comment] 2017-11-01 10:59
Got a problem here as well.

When the field is set on a taxonomy, eg. category, the rest api functionality breaks.

As far as i can see the problem is in the rest_api Decorator.php class on line 130.

In my case it is trying to get the 'term_id' but this is not available on the term object. It has to be just 'id'. When changing it to id everything is good.

`case 'term_meta':
return $object->term_id;
break;`

should be

`case 'term_meta':
	return $object->id;
	break;`

**Comment by atanas-angelov-dev** [comment] 2017-11-16 16:03
Fixed in 2.1.1 - closing.

**Closed by atanas-angelov-dev** 2017-11-16 16:03 UTC
Labels: bug, fixed in dev
