### ISSUE TITLE
1.5 Conditional UI

### ISSUE THREAD

**Issue by Santana1053** [htmlburger/carbon-fields#164] opened 2016-12-14 20:34 UTC
I noticed this update while using a conditional field inside of a tabbed-vertical complex field.
![image](https://cloud.githubusercontent.com/assets/10775656/21199769/8145f1b0-c20a-11e6-8296-3d884231054e.png)

Notice how the title of the field that was added is on top of the 'Clone / Remove' buttons from the complex field.
![image](https://cloud.githubusercontent.com/assets/10775656/21199778/8a3dba00-c20a-11e6-8a89-cbc690bc66be.png)

**Comment by yuliyan** [comment] 2016-12-15 09:44
@Santana1053 thanks for the report.

Could you please send the fields definition code?

**Comment by Santana1053** [comment] 2016-12-15 14:52
```
Container::make( 'theme_options', 'Theme Options' )
             ->add_fields( array(
                 Field::make( 'complex', 'tracking' )
                      ->set_layout( 'tabbed-vertical' )
                      ->setup_labels( array( 'singular_name' => 'Tracking Code', 'plural_name' => 'Tracking Codes' ) )
                      ->add_fields( 'custom', array(
                          Field::make( 'checkbox', 'all_pages', 'Show on every page' )
                               ->set_default_value( 'yes' ),
                          Field::make( 'association', 'page_selector' )
                               ->set_required( true )
                               ->set_conditional_logic( array( array( 'field' => 'all_pages' ) ) )
                               ->set_types( array(
                                   array(
                                       'type'      => 'post',
                                       'post_type' => 'post',
                                   ),
                                   array(
                                       'type'      => 'post',
                                       'post_type' => 'page',
                                   ),
                               ) ),
                      ) ),
             ) );
```

**Comment by yuliyan** [comment] 2016-12-19 07:58
It seems like this issue was caused by a bug with `display: flex` and `position: absolute` child elements in webkit browsers. However, it's fixed in 3925eb3.

**Closed by yuliyan** 2016-12-19 07:58 UTC
