### ISSUE TITLE
Javascript error when use ->where condition

### ISSUE THREAD

**Issue by bilalmalkoc** [htmlburger/carbon-fields#735] opened 2019-07-05 17:37 UTC
## Version

  - Carbon Fields: 3.1.2
  - WordPress: 5.2.2
  - PHP: 7.2

## Expected Behavior
Trying to edit post/page screen.

## Actual Behavior
Page doesn't opening. And shows many javascript errors.
<img src="https://i.vgy.me/iJHFq1.png">

## Container definition
```
use Carbon_Fields\Container;
use Carbon_Fields\Field;
use Carbon_Fields\Block;

$prefix = 'neon_';

/**
 * Post meta box
 */
function neon_post_meta_boxes() {
    global $prefix;

    // Post meta
    Container::make( 'post_meta', esc_html__( 'Post Statistics', 'neon' ) )
        ->where( 'post_type', '=', 'post' )
        ->add_fields(
            array(
                Field::make( 'text', $prefix . 'post_view_count', esc_html__( 'View count', 'neon' ) )->set_attribute( 'type', 'number' ),
                Field::make( 'text', $prefix . 'love_count', esc_html__( 'Love', 'neon' ) )->set_attribute( 'type', 'number' )->set_width( 20 ),
                Field::make( 'text', $prefix . 'angry_count', esc_html__( 'Angry', 'neon' ) )->set_attribute( 'type', 'number' )->set_width( 20 ),
                Field::make( 'text', $prefix . 'laugh_count', esc_html__( 'Laugh', 'neon' ) )->set_attribute( 'type', 'number' )->set_width( 20 ),
                Field::make( 'text', $prefix . 'sad_count', esc_html__( 'Sad', 'neon' ) )->set_attribute( 'type', 'number' )->set_width( 20 ),
                Field::make( 'text', $prefix . 'shock_count', esc_html__( 'Shock', 'neon' ) )->set_attribute( 'type', 'number' )->set_width( 20 ),
            )
        );

    // Post side meta (Layout)
    Container::make( 'post_meta', esc_html__( 'Post Options', 'neon' ) )
        ->where( 'post_type', '=', 'post' )
        ->set_context( 'side' )
        ->add_fields( array(
            Field::make( 'radio_image', $prefix . 'post_layout', esc_html__( 'Layout', 'noeon' ) )
                ->set_options( array(
                    'content_sidebar' => get_template_directory_uri() . '/inc/options/images/content_sidebar.jpg',
                    'sidebar_content' => get_template_directory_uri() . '/inc/options/images/sidebar_content.jpg',
                    'content'         => get_template_directory_uri() . '/inc/options/images/content.jpg',
                ) ),
            Field::make( 'select', $prefix . 'video_type', esc_html__( 'Video type' ), 'neon' )
                ->add_options( array(
                    'youtube' => esc_html__( 'Youtube', 'neon' ),
                    'vimeo'   => esc_html__( 'Vimeo', 'neon' ),
                    'direct'  => esc_html__( 'Direct link', 'neon' ),
                ) ),
            Field::make( 'text', $prefix . 'post_video_thumb', esc_html__( 'Featured video', 'neon' ) )
                ->set_help_text( esc_html__( 'Video ID if choose Vimeo or Youtube. Else, leave video direct link.', 'neon' ) ),
        ) );

}

add_action( 'carbon_fields_register_fields', 'neon_post_meta_boxes' );

/**
 * Page meta box
 */
function neon_page_meta_box() {
    global $prefix;

    Container::make( 'post_meta', esc_html__( 'Page Options', 'neon' ) )
        ->where( 'post_type', '=', 'page' )
        ->set_context( 'side' )
        ->add_fields( array(
            Field::make( 'checkbox', $prefix . 'empty_page', esc_html__( 'Empty page', 'neon' ) ),
            Field::make( 'radio_image', $prefix . 'post_layout', esc_html__( 'Layout', 'neon' ) )
                ->set_options( array(
                    'content_sidebar' => get_template_directory_uri() . '/inc/options/images/content_sidebar.jpg',
                    'sidebar_content' => get_template_directory_uri() . '/inc/options/images/sidebar_content.jpg',
                    'content'         => get_template_directory_uri() . '/inc/options/images/content.jpg',
                ) )
        ) );
}

add_action( 'carbon_fields_register_fields', 'neon_page_meta_box' );
```

## Steps to Reproduce the Problem

  1. Insall and activate carbon-fields plugin
  2. Call with require_once metabox.php (it includes above code)

## Comments
It shows this error only using `->where( 'post_type', '=', 'page' )` or -`>where( 'post_type', '=', 'post' )`

**Comment by RyanBerliner** [comment] 2019-07-09 19:51
I am experiencing a similar issue but in a strange edge case. 

I have a custom post type called `Foo` with key `foo_type`. I add a `post_meta` container with the condition `->where( 'post_type', '=', 'foo_type' )`. **I then get a white screen when trying open the new post screen of any post type (custom or default Wordpress) that _supports the editor._**

If I change my post type key to `foo_type_changed`, the problem is resolved _until I create a new `Foo` post._ Strangely, I have other custom post types that are identical to `Foo`, whose meta containers (also identical to `Foo`) do not cause the same problem.

The console is lit up similar to the screenshot in @bilalmalkoc's comment when I experience the white screens. Server error logs are not affected.

**Comment by bilalmalkoc** [comment] 2019-07-11 16:29
@RyanBerliner i can't deploy my theme because of this bug. And i am waiting for 5 days to fix this 😤

**Comment by kazztor-** [comment] 2019-07-13 02:40
Works on my end 
![bilalmalkoc-page](https://user-images.githubusercontent.com/6578687/61166007-51e9ec00-a4ed-11e9-9237-a3d2f52b5d61.gif)
![bilalmalkoc-post](https://user-images.githubusercontent.com/6578687/61166008-52828280-a4ed-11e9-99e0-ab14c8b74aa7.gif)

Maybe I'm missing something, and I'm sorry if this is not what your trying to fix, but the only difference in your code and mine is the yours is missing:
`add_action( 'after_setup_theme', 'crb_load' );
function crb_load() {
    require_once( 'vendor/autoload.php' );
    \Carbon_Fields\Carbon_Fields::boot();
}`

PHP 7.3.6
WordPress Version 5.2.2
htmlburger/carbon-fields (v3.1.2)

**Comment by bilalmalkoc** [comment] 2019-07-13 08:20
@kazztor- i am using plugin version. It includes crb_load action.

**Comment by kazztor-** [comment] 2019-07-15 23:38
@bilalmalkoc Hello again, I don't know if knowing that you can get the code running on a different environment helps you, but I've set up the plugin, added your code in a file named metabox.php and it worked. 

![bilalmalkoc-plugin](https://user-images.githubusercontent.com/6578687/61255789-b4cac580-a72f-11e9-964d-0e2bd2dc29df.gif)

PHP 7.3.6
WordPress Version 5.2.2
htmlburger/carbon-fields (v3.1.2)

**Comment by macronomicus** [comment] 2019-08-17 17:17
I got the same error using the regular non-gutenberg way of using cf containers from functions.php, unless i have the classic editor enabled in my theme (Divi) I get a wsod on the edit custom post type, with basically the same js errors as above.  It also clears up if I disable the editor "supports" totally in my custom content type.   Using this on the default post type does not appear to throw the error though, so perhaps for me its a conflict with CPT UI?  Thats what I used to create my custom post type.  
Hmm...  Suppose Carbon Fields requires a (Custom "Supports") registered to the post type?  https://docs.pluginize.com/article/28-third-party-support-upon-registration

The only plugin enabled on my blank test site is [Custom Post Type UI 1.6.2] And the latest Divi Theme that has its builder built in, I get the error whether divi is set to activate on the custom content type or not, and it is on the default post type in which the carbon fields container did display.  So its not Divi builder at least.  

Seems narrowed down to my custom post type.  I tried a ton of different settings and the only remaining bit I can think of is some carbon fields "Supports" needing to be registered as I said above.

I tested this with a basic setup of a few basic carbon fields in one container.

pantheon.io server cluster setup, local testing with lando + docker
htmlburger/carbon-fields (v3.1.3)
WordPress Version 5.2.2
PHP 7.3.5

**Comment by macronomicus** [comment] 2019-08-18 19:33
Just to update, for me at least, its some issue I couldn't figure with custom post type UI.  
Once I removed that plugin, and manually created my content type from a custom plugin it all worked just fine no errors.  I went ahead and installed carbon fields as a plugin too, so I could make it required by my plugin, and I moved the custom fields code into my content type plugin instead of the theme layer.  Yay happy camper!

Thanks so much for this great mod, WP is missing so many things im used to being standard in core in the Drupal world.  Thankfully WP has users like you that are contributing such great things.  Cheers!

**Comment by RyanBerliner** [comment] 2019-09-26 14:28
> I am experiencing a similar issue but in a strange edge case.
> 
> I have a custom post type called `Foo` with key `foo_type`. I add a `post_meta` container with the condition `->where( 'post_type', '=', 'foo_type' )`. **I then get a white screen when trying open the new post screen of any post type (custom or default Wordpress) that _supports the editor._**
> 
> If I change my post type key to `foo_type_changed`, the problem is resolved _until I create a new `Foo` post._ Strangely, I have other custom post types that are identical to `Foo`, whose meta containers (also identical to `Foo`) do not cause the same problem.
> 
> The console is lit up similar to the screenshot in @bilalmalkoc's comment when I experience the white screens. Server error logs are not affected.

I've just run into this issue again, with a little more context. If I remove editor support from the post type that is white screening, it no longer white screens, but the same `Could not find DOM element for container 'XYZ'` still shows in the console (with seemingly no effect on the page). This makes me think that this might not be the fatal error that is causing the white screen.

**Comment by hay** [comment] 2020-04-24 12:30
I also encountered this error (or at least, the `Could not find DOM element for container` Javascript error and the blank screen). This happened only in Firefox 75 (Mac), i had no problems in Chrome 80 (Mac). 

I'm not quite sure why, but i when i removed the `set_context('carbon_fields_after_title')` method from this piece of code i had no problems in Firefox anymore:

```php
add_action('carbon_fields_register_fields', function() {
    Container::make('post_meta', 'Book metadata')
        ->where('post_type', '=', 'book')
        ->set_context('carbon_fields_after_title')
        ->add_fields([
            Field::make('textarea', Option::name('remark'), __('Remark'))
                ->set_rows(3)
        ]);
});
```

**Comment by jorostoyanov** [comment] 2021-07-28 16:38
The issue is fixed in the latest version.

Please update

**Closed by jorostoyanov** 2021-07-28 16:38 UTC
