### ISSUE TITLE
Removing the last item in a multiselect creates a map error in the console.

### ISSUE THREAD

**Issue by dtracey-fi** [htmlburger/carbon-fields#1205] opened 2023-11-26 22:53 UTC
## Version

  - Carbon Fields: 3.6.2
  - WordPress: 5.4.1
  - PHP: 8.0

## Expected Behavior
The user should be able to add all options to the multiselect field, and then remove them all.

## Actual Behavior
Upon removing the last item in the multiselect, an error appears in the console, and the last item isn't removed.

`Uncaught TypeError: Cannot read properties of null (reading 'map')
    at Object.onChange (core.min.js?ver=3.6.2:1:349535)
    at n.value (core.min.js?ver=3.6.2:1:348174)
    at e.onChange (core.min.js?ver=3.6.2:1:347471)
    at r.onChange (core.min.js?ver=3.6.2:1:322858)
    at r.removeValue (core.min.js?ver=3.6.2:1:324239)
    at onClick (core.min.js?ver=3.6.2:1:341192)
    at Object.Xa (react-dom.min.js?ver=18.2.0:10:105741)
    at B (react-dom.min.js?ver=18.2.0:10:10501`

## Container definition
```php
Field::make('multiselect', 'test', 'Options')->add_options([
					'one' => 'One',
					'two' => "Two",
				]),
```

## Steps to Reproduce the Problem

  1. Add One and Two to the multiselect field.
  2. Remove One and Two from the multiselect field.

**Comment by henrik-dons** [comment] 2024-02-02 18:58
Any updates on this?

**Comment by Youdaman** [comment] 2024-03-13 06:06
Looks to be a duplicate of https://github.com/htmlburger/carbon-fields/issues/1182

Also waiting for an update on this please.

**Comment by paul-brain** [comment] 2024-07-20 06:33
Join this and waiting for updates...

**Comment by atanas-vasilev-dev** [comment] 2024-07-24 06:04
Fixed here:
https://github.com/htmlburger/carbon-fields/commit/0103f0da9cac6ab9adfc067eb9fbacc4690f5b0b
It will be included in next release

**Closed by atanas-vasilev-dev** 2024-07-24 06:04 UTC

**Comment by martin-neumann-gurus** [comment] 2024-07-26 13:46
Wow, that is a much needed fix for me. Looking anxiously for this release.

**Comment by atanas-vasilev-dev** [comment] 2024-07-31 08:39
The fix for this issue is now released in https://github.com/htmlburger/carbon-fields/releases/tag/v3.6.5
