### ISSUE TITLE
Fatal Error Installing via Composer on Bedrock

### ISSUE THREAD

**Issue by christianmagill** [htmlburger/carbon-fields#72] opened 2016-08-07 23:02 UTC
When installing via composer on a Roots / Bedrock project.

Fatal error: Call to undefined function trailingslashit() in /srv/www/influencebydesign/htdocs/vendor/htmlburger/carbon-fields/carbon-fields.php on line 13

**Comment by m1r0** [comment] 2016-08-09 06:36
Duplicate of https://github.com/htmlburger/carbon-fields/issues/5

**Closed by m1r0** 2016-08-09 06:36 UTC
