### ISSUE TITLE
ReferenceError: event is not defined for oEmbed Field

### ISSUE THREAD

**Issue by carstenwawer** [htmlburger/carbon-fields#537] opened 2018-05-29 12:38 UTC
## Version

  - Carbon Fields: 2.2
  - WordPress: 4.9.6
  - PHP: 7.2

## Expected Behavior
I wrote a very simple Plugin to test the OEmbed-Fields of Carbonfields. It should display on the backend and work as expected. I'm working on a pretty complex Multisite-Network with many plugins activated. So i tried the Test-Plugin on a fresh Wordpress-Docker-Setup and ran into the described behaviour again.

## Actual Behavior
When navigating the Page with the OEmbed-Field, the oEmbed-Proxy-URL is called succesfully, but then a Javascript-Error is thrown. Because of that the oEmbed is not displayed.

```javascript
ReferenceError: event is not defined carbon.core.min.js:9:16935

Source map error: request failed with status 404
Resource URL: http://localhost/wp-content/plugins/development-plugin/vendor/htmlburger/carbon-fields/assets/dist/carbon.core.min.js?ver=2.2.0

Source Map URL: carbon.core.min.js.map

ReferenceError: event is not defined[Learn More] carbon.core.min.js:9:16935
```

## Plugin Code
```php
use Carbon_Fields\Container;
use Carbon_Fields\Field;

add_action( 'plugins_loaded', function(){
	require_once( 'vendor/autoload.php' );
    \Carbon_Fields\Carbon_Fields::boot();
} );

add_action( 'carbon_fields_register_fields', function(){
		
	Container::make( 'theme_options', 'Test' )
		->add_fields( array(
			Field::make( 'html', 'crb_information_text' )
				->set_html( '<h1>Lorem ipsum</h1><p>Quisque mattis ligula.</p>' ),
			Field::make( 'oembed', 'crb_oembed' )
		) );
});
```

## Composer JSON
```php
{
    "require": {
        "htmlburger/carbon-fields": "^2.2"
    }
}

```

## Steps to Reproduce the Problem

  1. I run into the problem on a fresh (Docker-)Wordpress-Installation with all actual Updates but no other Plugins activated. So it should be enough to take my plugin code, run composer und activate it

**Comment by deqngeorgiev** [comment] 2018-06-11 07:42
Hi @carstenwawer,

Thank you for your feedback!

I've tested your case and there was an issue with the oEmbed field on some browsers.

The issue is now fixed on the development branch (https://github.com/htmlburger/carbon-fields/commit/a7d535e715cfe78a7817b68a58ee9c9ec0fe6095)

**Comment by alessandrotesoro** [comment] 2018-09-01 11:12
Hi @deqngeorgiev 

Was the fix released? I'm currently running into the same exact issue with version 2.2 of the library.

**Comment by alessandrotesoro** [comment] 2018-09-06 12:33
@deqngeorgiev thank you sounds great.

**Closed** 2020-11-05 16:38 UTC
Labels: [status] fixed in dev
