### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Carbon_Fields\Carbon_Fields' not found on theme/frontend

### ISSUE THREAD

**Issue by Obvio** [htmlburger/carbon-fields#280] opened 2017-07-14 15:35 UTC
Hi, I've installed CF 2.0.1 via composer in my theme directory, and followed the steps to setup fields in the admin: all works great there, but when I access the theme itself (ie. trying to view the home page in the browser) I get this error:

```
Fatal error: Uncaught Error: Class 'Carbon_Fields\Carbon_Fields' not found in /var/www/wp-content/themes/THE_THEME/functions.php on line 22

Fatal error: Uncaught Error: Class 'Carbon_Fields\Carbon_Fields' not found in /var/www/wp-content/themes/THE_THEME/functions.php on line 22
```

functions.php line 22 actually has `Carbon_Fields\Carbon_Fields::boot();` inside the `crb_load` function:

```
function crb_load() {
	require_once( 'vendor/autoload.php' );
	Carbon_Fields\Carbon_Fields::boot();
}

add_action( 'after_setup_theme', 'crb_load' );
```

also, something to note, when installing it from _within_ the theme directory in creates a `wp-content/plugins/carbon-fields` within the theme's directory itself, so it looks like `THE_THEME/wp-content/plugins/carbon-fields`..

thanks!

**Comment by dmhendricks** [comment] 2017-07-15 18:57
Maybe try?
```
require_once( __DIR__ . '/vendor/autoload.php' );

add_action( 'plugins_loaded', array( 'Carbon_Fields\\Carbon_Fields', 'boot' ) );
```

Regarding the folder path, you can change it with [mnsami/composer-custom-directory-installer](https://github.com/mnsami/composer-custom-directory-installer). Example: 
https://github.com/htmlburger/carbon-fields/issues/273

**Comment by atanas-angelov-dev** [comment] 2017-07-17 06:14
> also, something to note, when installing it from within the theme directory in creates

This is because the package has a type of `wordpress-plugin` which combined with `composer/installer` installs it in `wp-content/plugins/carbon-fields` relative to your composer.json position. This means that when you are installing it from your theme you should add this to your composer.json:

**Comment by atanas-angelov-dev** [comment] 2017-07-17 06:18
> Fatal error: Uncaught Error: Class 'Carbon_Fields\Carbon_Fields' not found

This is 99% caused by the autoloader not being included. Please make sure your require statement points to the correct `autoload.php` file path generated by composer.

> also, something to note, when installing it from within the theme directory in creates

This is because the package has a type of `wordpress-plugin` which combined with `composer/installer` installs it in `wp-content/plugins/carbon-fields` relative to your composer.json position. This means that when you are installing it from your theme you should add this to your composer.json:
```json
"extra": {
    "installer-paths": {
        "vendor/{$vendor}/{$name}/": ["type:wordpress-plugin"]
    }
}
```

___Note:___ we may push an update this week that removes the need for this.

**Comment by Obvio** [comment] 2017-07-17 12:52
got it thanks, the quickstart on https://carbonfields.net/docs/carbon-fields-quickstart/?crb_version=2-0-0 instructs to run composer from within the theme directory.

**Comment by atanas-angelov-dev** [comment] 2017-07-17 14:43
2.0.2 has been released which changes how Carbon Fields are installed.
The main package is no longer marked as a `wordpress-plugin` so it will install in the vendor directory where your composer.json is (i.e. the mentioned `extra` key is no longer needed if you are installing CF in your theme).

The plugin loader file is now it's own composer package:
https://github.com/htmlburger/carbon-fields/releases/tag/2.0.2

**Closed by atanas-angelov-dev** 2017-07-17 14:43 UTC
Labels: question
