### ISSUE TITLE
Media Gallery image editing

### ISSUE THREAD

**Issue by kyosifov** [htmlburger/carbon-fields#656] opened 2019-02-01 15:14 UTC
## Version

  - Carbon Fields: 3.0.2
  - WordPress: 5.0.3
  - PHP: 7.2

## Expected Behavior
In carbon fields 2 you can edit the image metadata like (title, caption etc...), but the feature is not present in carbon-fields 3

## Actual Behavior
Can't edit the image metadata

## Steps to Reproduce the Problem

  1.Create a `media_gallery` field

### Carbon fields 2
https://imgur.com/a/zWeYa4f

### Carbon fields 3
https://imgur.com/a/neRPanp

**Comment by viterzbayraku** [comment] 2020-07-21 08:58
I agree too. This is a very important feature.

**Comment by underdoeg** [comment] 2020-10-15 13:47
Yes, I am missing this feature as well

**Comment by mamunur105** [comment] 2020-10-31 12:22
I am still missing this feature.

**Comment by jorostoyanov** [comment] 2021-03-26 22:55
Duplicate of https://github.com/htmlburger/carbon-fields/issues/937

**Closed by jorostoyanov** 2021-03-26 22:55 UTC
Labels: feature
