### ISSUE TITLE
post_parent of files in custom post types

### ISSUE THREAD

**Issue by batz-bar** [htmlburger/carbon-fields#249] opened 2017-06-12 16:34 UTC
When file fields is added to post type "page" "post" the attachment is saved with post_parent value as the post id which the fields are attached. 
In custom post types files, the post_parent is 0 (not set).
The reason is because the file upload media form doesn't send to the backend parameter "post_id" unlike the post type "page" "post" (the build in wp post types) that the form sends the parameter "post_id".
How could custom post type files attachments could be set to save with the post_id as post_parent?

**Comment by atanas-angelov-dev** [comment] 2017-06-13 06:53
Hi @batz-bar ,

Unfortunately we were unable to reproduce this issue - a clean WordPress install (tested 4.7 and 4.8) with Carbon Fields properly sends the post_id along with file uploads for custom post types:

```
------WebKitFormBoundaryYzeTBBCALaTSLqQL
Content-Disposition: form-data; name="name"

coffe-table.jpg
------WebKitFormBoundaryYzeTBBCALaTSLqQL
Content-Disposition: form-data; name="action"

upload-attachment
------WebKitFormBoundaryYzeTBBCALaTSLqQL
Content-Disposition: form-data; name="_wpnonce"

f1fce15c0c
------WebKitFormBoundaryYzeTBBCALaTSLqQL
Content-Disposition: form-data; name="post_id"

60
------WebKitFormBoundaryYzeTBBCALaTSLqQL
Content-Disposition: form-data; name="async-upload"; filename="coffe-table.jpg"
Content-Type: image/jpeg


------WebKitFormBoundaryYzeTBBCALaTSLqQL--
```

**Comment by batz-bar** [comment] 2017-06-14 14:09
Hi,
Thanks for the quick reply.
Maybe the way I'm adding the fields is different. 
Could you please paste here the code you added the fields and post type and I will see if it works?
Thanks!

**Comment by atanas-angelov-dev** [comment] 2017-06-14 14:24
I'm not using any special field definition code - it's as simple as this:
`Field::make( 'file', 'crb_file', __( 'File', 'crb' ) ),`
This is most probably due to a plugin or other third party code that is interfering in your case.

I'm closing this ticket - feel free to reopen it with a reproduce case.

**Closed by atanas-angelov-dev** 2017-06-14 14:24 UTC
