### ISSUE TITLE
Complex field without `Add Entry`

### ISSUE THREAD

**Issue by matgargano** [htmlburger/carbon-fields#436] opened 2017-12-09 02:39 UTC
Can you hide the Add Entry button (and collapse all) - natively within this plugin. The use case:

Having a Complex field with prepopulated social networks (Twitter, Facebook, Gort, etc.) and allowing users to reorder the social networks in the backend to set the order they should be output on the frontend. I would create a complex field with pre-populated display fields (https://github.com/statenweb/carbon-field-display/) and allow them to save the order. In this case I would not want to allow the admin to add fields. Can they be suppressed natively, it didn't appears so looking at the API?

**Comment by ght** [comment] 2017-12-10 07:33
Not sure if it helps, but you can set a maximum number of entries with e.g. `->set_max( 3 )` and there won't be an "Add entry" button if there are already 3 entries.

**Comment by matgargano** [comment] 2017-12-10 16:13
It kinda helps --- but what if I want to introduce a filter that will allow
me or users to add fields themselves that number would need to be accounted
for.  Thanks tho!

**Comment by atanas-angelov-dev** [comment] 2017-12-11 07:17
Closing as a duplicate of #234 .

Feel free to React with a 👍 on that issue to show your support for it!

**Closed by atanas-angelov-dev** 2017-12-11 07:17 UTC
Labels: duplicate
