### ISSUE TITLE
Call to undefined function carbon_get_theme_option

### ISSUE THREAD

**Issue by filippozanardo** [htmlburger/carbon-fields#294] opened 2017-07-28 14:01 UTC
Hi,
i don't know if it's a bug or i'm doing something wrong in a plugin i'm developing i can create field and  save values but when i try to get back options value i got that error, if i put in loader after the line with:

```
include_once( \Carbon_Fields\DIR . '/core/functions.php' );
var_dump( \Carbon_Fields\DIR . '/core/functions.php' );
```

the correct path is returned.

The stange things is also that if i call directly helper method:

`Helper::get_theme_option( 'myvalue','' );`

return am empty string.

I think that carbon boot correctly i use something like:

`add_action( 'plugins_loaded', array( 'Carbon_Fields\\Carbon_Fields', 'boot' ) );`

Any  clues?
Thanks

**Comment by atanas-angelov-dev** [comment] 2017-07-28 14:04
Hi @filippozanardo ,

Can you check if you are calling carbon_get_theme_option() too early (i.e. before `boot` is called)?

**Comment by filippozanardo** [comment] 2017-07-28 14:13
Is there a way to do that?
I tried after class construct , after creating some field, i change the hook in init with no luck.

**Comment by atanas-angelov-dev** [comment] 2017-07-28 14:15
I'll need to see your code snippet and where it is executed exactly in order to be able to determine if you are using the getter functions too early.

**Comment by filippozanardo** [comment] 2017-07-28 14:18
Sure here's my last try:
https://gist.github.com/filippozanardo/239127e840ed00ff466e254cc72201b9

**Comment by atanas-angelov-dev** [comment] 2017-07-28 14:24
```php
add_action( 'init', array( 'Carbon_Fields\\Carbon_Fields', 'boot' ) );
add_action( 'after_setup_theme', array( self::$instance, 'test' ) );
```

The above code shows that the `boot()` method is called in the `init` hook while `test()` is called in the `after_setup_theme` hook. If you look at the [WordPress action reference](https://codex.wordpress.org/Plugin_API/Action_Reference) you will see that `after_setup_theme` is called before `init` so essentially `test()` is called before `boot()`.

If we change the test hook to `wp`, for example, your code should work:

```php
add_action( 'init', array( 'Carbon_Fields\\Carbon_Fields', 'boot' ) );
add_action( 'wp', array( self::$instance, 'test' ) );
```

**Comment by filippozanardo** [comment] 2017-07-28 14:36
Ok cool i was tryng with hooks the problem is that return an empty string:

var_dump( carbon_get_theme_option('rv_colors') );

in the database i got:


278 | _rv_colors | a:2:{i:0;a:2:{s:5:"value";s:1:"_";s:8:"rv_color";a... | no
-- | -- | -- | --

The first underscore is added by carbon i think.

**Comment by filippozanardo** [comment] 2017-07-28 15:24
With get_option i get the correct value:

`var_dump( carbon_get_theme_option('rv_colors') );
var_dump( carbon_get_theme_option('_rv_colors') );
var_dump( get_option( '_rv_colors' ) );`

output:

`

string(0) ""
--
  | string(0) ""
  | array(2) {
  | [0]=>
  | array(2) {
  | ["value"]=>
  | string(1) "_"
  | ["rv_color"]=>
  | array(1) {
  | [0]=>
  | array(1) {
  | ["value"]=>
  | string(7) "#df5555"
  | }
  | }
  | }
  | [1]=>
  | array(2) {
  | ["value"]=>
  | string(1) "_"
  | ["rv_color"]=>
  | array(1) {
  | [0]=>
  | array(1) {
  | ["value"]=>
  | string(7) "#254cd9"
  | }
  | }
  | }
  | }

`

strange i'm still debugging but can't find why this happen.

**Comment by dmhendricks** [comment] 2017-07-28 16:34
Interesting that this appeared in my inbox. I was going to post ask about it yesterday (I had the exact same issue), but since it was happening on a multisite I just assumed it was some rubbish related to that, so I wrote my own `carbon_get_theme_option` alternative. I did notice that CRB started prepending an underscore to option_name's in the DB - I'm not sure when that changed. I tried adding an underscore to the field name on get, but no love.

It could be an order of operations issue, however, these plugins worked fine in previous versions... I think... As said, I wasn't sure what was causing it and thought that I might have changed something. [#mystery](https://twitter.com/hashtag/mystery)

**Comment by atanas-angelov-dev** [comment] 2017-07-31 06:16
All keys are now standardized which is why you see the underscores.
As for the issue at hand - CF 2.0 does not save serialized values anymore but you have a serialized value in the database - were you using 1.x before upgrading to 2.0 or have you modified the saving process or the field type after data has been saved to the database?

**Comment by filippozanardo** [comment] 2017-07-31 07:30
Hi,
for the serialized values i use this: https://carbonfields.net/docs/guides-serialized-datastore/?crb_version=2-0-0

I have other fields that are not serialized, but the problem is that the function carbon_get_theme_option didn't return anything, also the helper seems returning a blank string.

I think also dmhendricks have the same problem, with 1.6 everythings works perfect.

**Comment by atanas-angelov-dev** [comment] 2017-07-31 07:47
We'll need a reproduction case in order to investigate (exact CF version used, field definitions, code that calls carbon_get_theme_option etc.)

**Comment by filippozanardo** [comment] 2017-07-31 07:59
Hi,
version is composer latest 2.0.4.

this is the code for field definitions:
`Container::make('theme_options', 'Redbubble')
            ->add_fields(
                array(
                    Field::make("html", $this->prefix . 'title')
                        ->set_datastore( new Serialized_Theme_Options_Datastore() )
                        ->set_html('<h1>Bubble Options</h1>'),
                    Field::make("set", $this->prefix . 'enabled_on', __( 'Enable on', 'redvolver' ))
                        ->set_datastore( new Serialized_Theme_Options_Datastore() )
                        ->set_options(array( $this, 'get_post_types' )),
                    Field::make("text", $this->prefix . 'default_number', __( 'Item numbers', 'redvolver' ))
                        ->set_datastore( new Serialized_Theme_Options_Datastore() ),
                    Field::make("select", $this->prefix . 'default_type', __( 'Default Type', 'redvolver' ))
                        ->set_datastore( new Serialized_Theme_Options_Datastore() )
                        ->set_options(array( $this, 'get_default_types' )),
                    Field::make("file", $this->prefix . 'default_image', __( 'Default Image', 'redvolver' ))
                    ->set_datastore( new Serialized_Theme_Options_Datastore() )
                    ->set_conditional_logic(array(
                        'relation' => 'AND',
                        array(
                            'field' => $this->prefix . 'default_type',
                            'value' => 'image',
                            'compare' => '=',
                        )
                    )),
                    Field::make("text", $this->prefix . 'default_font_class', __( 'Default font class', 'redvolver' ))
                    ->set_datastore( new Serialized_Theme_Options_Datastore() )
                    ->set_conditional_logic(array(
                        'relation' => 'AND',
                        array(
                            'field' => $this->prefix . 'default_type',
                            'value' => 'font',
                            'compare' => '=',
                        )
                    )),
                    //Field::make("textarea", $this->prefix . 'default_custom_html', __( 'Default custom Html', 'redvolver' ))
                        //->set_rows(4),
                    Field::make("checkbox", $this->prefix . 'fixed_size', __( 'Fixed Size', 'redvolver' ))
                        ->set_datastore( new Serialized_Theme_Options_Datastore() )
                        ->help_text(__( 'Enable to fix item size to max size', 'redvolver' )),
                    Field::make("text", $this->prefix . 'min_size', __( 'Min Size', 'redvolver' ))
                        ->set_datastore( new Serialized_Theme_Options_Datastore() )
                        ->set_default_value(50),
                    Field::make("text", $this->prefix . 'max_size', __( 'Max Size', 'redvolver' ))
                        ->set_datastore( new Serialized_Theme_Options_Datastore() )
                        ->set_default_value(200),
                    Field::make("checkbox", $this->prefix . 'random_speed', __( 'Random Speed Animation', 'redvolver' ))
                        ->set_datastore( new Serialized_Theme_Options_Datastore() )
                        ->help_text(__( 'Random Speed Animation every item have different random speed', 'redvolver' )),
                    Field::make("select", $this->prefix . 'animation_speed', __( 'Animation Speed', 'redvolver' ))
                        ->set_datastore( new Serialized_Theme_Options_Datastore() )
                        ->set_options(array( $this, 'get_default_speed' ))
                        ->set_default_value(1),
                    Field::make("checkbox", $this->prefix . 'random_opacity', __( 'Random Opacity', 'redvolver' ))
                        ->set_datastore( new Serialized_Theme_Options_Datastore() )
                        ->help_text(__( 'Random Opacity', 'redvolver' )),
                    Field::make("select", $this->prefix . 'default_opacity', __( 'Default Opacity', 'redvolver' ))
                        ->set_datastore( new Serialized_Theme_Options_Datastore() )
                        ->set_options(array( $this, 'get_default_opacity' ))
                        ->set_default_value(0.5),
                    Field::make("checkbox", $this->prefix . 'random_colors', __( 'Random Colors', 'redvolver' ))
                        ->set_datastore( new Serialized_Theme_Options_Datastore() )
                        ->help_text(__( 'Random Colors if enabled override custom colors', 'redvolver' )),
                    Field::make('complex', $this->prefix . 'colors',__( 'Custom Colors', 'redvolver' ))
                        ->set_datastore( new Serialized_Theme_Options_Datastore() )
                        ->set_layout('tabbed-horizontal')
                        ->add_fields(array(
                            Field::make("color", $this->prefix . 'color', __( 'Custom Color', 'redvolver' ))
                        )),
                    Field::make('complex', $this->prefix . 'colors2',__( 'Custom Colors', 'redvolver' ))
                        ->set_layout('tabbed-horizontal')
                        ->add_fields(array(
                            Field::make("color2", $this->prefix . 'color', __( 'Custom Color', 'redvolver' ))
                        )),
                )
        );`

And i use carbon_get_theme_option in this gist i send you some day ago:
https://gist.github.com/filippozanardo/239127e840ed00ff466e254cc72201b9

Let me know if you need something more thanks

**Comment by atanas-angelov-dev** [comment] 2017-07-31 08:02
Can you please add the full value stored in the database for the field as well (sorry I missed to mention this)?

**Comment by filippozanardo** [comment] 2017-07-31 08:06
here:
https://gist.github.com/filippozanardo/e9538146e4e01205f8b269baff4a0c83

**Comment by filippozanardo** [comment] 2017-07-31 08:28
Hi,
debuggin the retrieval i got this in Helper class if i do something like on this function:

`public static function get_value`
and i do var_dump:
`var_dump( $object_id, $container_type, $container_id, $field_name );`

i got:

NULL
string(13) "theme_options"
string(0) ""
string(9) "rv_colors"

Next in the get_field_clone if i put:
`var_dump('field clone',$field);`

I got:

string(11) "field clone"
NULL

Thanks

**Comment by filippozanardo** [comment] 2017-07-31 12:17
Diggin through the code i saw that in Repository.php on this function:

public function get_containers( $type = null ) {
		$raw_containers = $this->containers;
		var_dump('raw',$raw_containers,$type);

i saw that raw_containers are empty so in the function get_field_in_containers the field is null everytime, why i didn't find out yet.

**Comment by atanas-angelov-dev** [comment] 2017-08-01 08:23
This code has still not been updated as mentioned:
```php
add_action( 'init', array( 'Carbon_Fields\\Carbon_Fields', 'boot' ) );
add_action( 'after_setup_theme', array( self::$instance, 'test' ) );
```
(Lines 44-45 from [the gist you sent](https://gist.github.com/filippozanardo/239127e840ed00ff466e254cc72201b9))

Essentially, this code attempts to load a field's value before Carbon Fields has been booted.

Please refer to this [comment](https://github.com/htmlburger/carbon-fields/issues/294#issuecomment-318665880) in this thread.

**Comment by filippozanardo** [comment] 2017-08-01 08:30
Hi,
here's the updated gist:
https://gist.github.com/filippozanardo/0ae17d206f7fecd01321438f946ba029

**Comment by filippozanardo** [comment] 2017-08-01 09:27
With previous version "1.6" i didn't have this problem, i'm rewriting code to update to latest version.

**Comment by atanas-angelov-dev** [comment] 2017-08-01 13:12
I replicated your field and added the serialized value to the database and everything works as expected:

Definition:
```php
Field::make('complex', 'rv_colors',__( 'Custom Colors', 'redvolver' ))
	->set_datastore( new Serialized_Theme_Options_Datastore() )
	->set_layout('tabbed-horizontal')
	->add_fields(array(
		Field::make("color", 'rv_color', __( 'Custom Color', 'redvolver' ))
	)),
```

Output code:
```php
print_r( carbon_get_theme_option( 'rv_colors' ) );
```

Output result:
```php
Array
(
    [0] => Array
        (
            [_type] => _
            [rv_color] => #df5555
        )

    [1] => Array
        (
            [_type] => _
            [rv_color] => #254cd9
        )

)
```

Can you please make sure your latest test does indeed call carbon_get_theme_option() AFTER `boot` has been called?
If you still have the issue then I will need a repro case in order to investigate further.

**Comment by filippozanardo** [comment] 2017-08-01 13:19
Hi,
in the previous gist i think i called carbon_get_theme_option after boot or am i wrong?
Or i have to boot also in the class where fields are defined?
Thanks

**Comment by atanas-angelov-dev** [comment] 2017-08-01 13:21
It appears you are calling it correctly, however, I simply cannot reproduce the problem. I will need a full reproduce case in order to investigate the issue further.

**Comment by filippozanardo** [comment] 2017-08-01 13:22
Kk i set up a repository and give you access.
Thanks

**Comment by dmhendricks** [comment] 2017-08-01 18:19
> I think also dmhendricks have the same problem, with 1.6 everythings works perfect.

I'm not using the serialized datastore for this one, and I do not believe that I'm doing anything atypical. I'm using the same order-of-operations and procedures that I use on my other sites.

The only thing that I can think of that is different is that it's multisite (the other sites that I upgraded are not), however, this does not seem to be a relevant factor given what filippozanardo has said.

I updated another client's site to 2.0.4 yesterday and it seems to be functioning as expected. I'm not terribly concerned as I have a workaround for this one site that is affected. Notes:

* Yes, this site started on 1.6.0. (most of mine started on various versions - some started on 1.5.0, some on 1.6.0, and the newer ones start with 2.0.x).
* I did switch this site from loading it via composer to loading it via my own plugin (which has worked fine with other sites). I am aware that there could be an order-of-operations issue there, however, it is (unless I've made a silly mistake, which is possible) the same process and code that I use on my other sites.
* I know that Carbon Fields is loading before I define my Containers and Fields - they load fine and can pull/update field values. Those classes are also instantiated after CF boot and with the same init function. `add_action( 'carbon_fields_loaded', array( $this, 'load_plugin_classes_and_do_magic' ) );`
* I also have my plugins do a CF version check before it does anything (in case a version <2.0.0 is loaded before 2.x does). If CF >=2.0.0 then load plugin logic, else show dependency admin_notice.

I just thought I would mention it. I probably just missed something subtle. If I get time, I can try loading it via Composer again since I don't really have a good example that I can provide for you (private site/code that would be difficult to reproduce while removing enough not to break NDA).

**Comment by atanas-angelov-dev** [comment] 2017-09-07 07:13
Closing due to lack of reproduce case.
Feel free to reopen with one if the issue persists on the latest version (2.0.4 at this time)

**Closed by atanas-angelov-dev** 2017-09-07 07:13 UTC

**Comment by filippozanardo** [comment] 2017-09-21 10:59
Hi again,
can be that on "frontend" there is a bug?
What i mean is if i'm on wordpress backend carbon_get_theme_option works, if i call on the frontend keeps returning empty string.

`add_action( 'after_setup_theme', array( $this, 'carbon_boot' ) );`
`add_action( 'init', array( $this, 'bo' ), 999 );`

`public function carbon_boot() {`
		`\Carbon_Fields\Carbon_Fields::boot();`
		`$rv_default_number = carbon_get_theme_option('rv_colors');`
	`}`

	`public function bo() {`
		`$rv_default_number = carbon_get_theme_option('rv_colors');`
        `var_dump( carbon_get_theme_option('rv_colors') );`
	`}`

attached a screenshot.

![frontend](https://user-images.githubusercontent.com/12711982/30692647-b49acb2c-9ecc-11e7-9780-45d48e2173d6.png)
![backend](https://user-images.githubusercontent.com/12711982/30692650-b859b0fc-9ecc-11e7-87b1-e4f1348564e0.png)

**Comment by atanas-angelov-dev** [comment] 2017-09-21 11:16
Fields are not available immediately after `::boot()`  so the call in `carbon_boot()` will not work (fields are registered in `init` with priority of 0 so any hook after that is OK).

As for the front-end screenshot - I really can't tell what's going on with just that screenshot - it would be more useful if I can see what the source output of the page is instead.

**Comment by filippozanardo** [comment] 2017-09-21 11:38
Hi,
i'm calling on:
`add_action( 'init', array( $this, 'bo' ), 999 );`

So the field should be registered.
here 's the full code the strange behaviour is that on backend the code works on frontend not.

https://gist.github.com/filippozanardo/f026220a2d94fe3fc33db3fdd0c08b49

**Comment by atanas-angelov-dev** [comment] 2017-09-21 11:45
I meant the resulting front-page source (outputted html) so that I can see what exactly is output by the `var_dump()`.

Looking at your php source everything seems fine but I don't see where you define your fields (make sure they are defined in the `carbon_fields_register_fields` hook).

**Comment by filippozanardo** [comment] 2017-09-21 11:52
Hi,
this is the class that define fields:
https://gist.github.com/filippozanardo/b0d4743035f024c1cb75b54072154f54

here's the outputted html:
https://gist.github.com/filippozanardo/a65a928c047dbf56391ad63546342938

**Comment by atanas-angelov-dev** [comment] 2017-09-21 11:59
```php
if ( is_admin() ) {
	include_once( 'includes/admin/class-redvolver-bubble-admin.php' );
	// ...
};
```

This means you load your class that defines your fields only in the back-end so your fields never end up being defined during front-end requests.

**Comment by filippozanardo** [comment] 2017-09-21 12:04
ok now works, i though that retrieving fields from database is not related to registering field.
I mean with get_option you can retrieve everywhere.

**Comment by atanas-angelov-dev** [comment] 2017-09-21 12:08
Yes, with `get_option()` / `get_*_meta()` you can retrieve at any point without fields being registered but you will get raw data - with `carbon_get_*()` you will get formatted data in an appropriate for the specific field format which is why you need to have fields defined before you can fetch values for them with `carbon_get_*()`.

**Comment by filippozanardo** [comment] 2017-09-21 12:40
kk understood thanks
