### ISSUE TITLE
Carbon Complex Repeater Field is not supporting more than 160 items.

### ISSUE THREAD

**Issue by yubarajrai** [htmlburger/carbon-fields#699] opened 2019-04-01 07:20 UTC
## Version

  - Carbon Fields: 3.*
  - WordPress: 5.*
  - PHP: 7.*

## Expected Behavior
_I need to add at least 365 items in a page_

## Actual Behavior
_The repeater field having association field is not supporting more than 160 items. 
When I try to add more than 160 items, It is automatically removing itself when I update to save_

## Steps to Reproduce the Problem

  1. Create Repeater Field with association field
  2. Add items more than 160

**Comment by ChipRyan** [comment] 2019-04-03 17:45
What are your php.ini values for **max_input_vars** and **post_max_size**?

**Comment by jorostoyanov** [comment] 2020-11-05 15:17
As @ChipRyan suggested, the issue is not connected with Carbon Fields itself, but rather with your server settings.

As this ticket hasn't seen any response, I am closing it. Feel free to re-open for further discussion.

**Closed by jorostoyanov** 2020-11-05 15:17 UTC
