### ISSUE TITLE
New field type for free mapping service

### ISSUE THREAD

**Issue by deqngeorgiev** [htmlburger/carbon-fields#524] opened 2018-05-04 11:45 UTC
Google has announced that they will change their API to require billing account in order to get an API key so a new field type with a free mapping service ([Leaflet](https://leafletjs.com/) for example) will be added in future releases.

**Comment by jorostoyanov** [comment] 2021-03-26 23:12
Duplicate of https://github.com/htmlburger/carbon-fields/issues/613

**Closed by jorostoyanov** 2021-03-26 23:12 UTC
Labels: enhancement
