### ISSUE TITLE
Radio buttons not showing saved value

### ISSUE THREAD

**Issue by davejtoews** [htmlburger/carbon-fields#588] opened 2018-09-24 20:01 UTC
## Version

  - Carbon Fields: 2.2
  - WordPress: 4.9.8
  - PHP: 7.1

## Expected Behavior
When using two similar radio buttons on the same page, I expect both to show their saved value on page reload after save.

## Actual Behavior
No value appears to be selected.
<img width="178" alt="screen shot 2018-09-24 at 1 50 54 pm" src="https://user-images.githubusercontent.com/9664035/45975549-be990600-c001-11e8-839a-7e767f7b61d5.png">
<img width="116" alt="screen shot 2018-09-24 at 1 50 57 pm" src="https://user-images.githubusercontent.com/9664035/45975552-bfca3300-c001-11e8-8dcc-3ae82dceb1b4.png">

## Container definition
Field Grop definition:

    <?php

    namespace App\Fields;

    use Carbon_Fields\Field;

    class FeaturedPanel extends FieldGroup
    {
        public static function getFields(string $prefix = '')
        {
            return [
                Field::make('radio', $prefix . 'feature_orientation', 'Title Orientation')
                    ->add_options([
                        'left' => 'Left',
                        'right' => 'Right'
                    ]),
                Field::make('text', $prefix . 'feature_title', 'Title'),
                Field::make('textarea', $prefix . 'feature_body', 'Body'),
                Field::make('text', $prefix . 'feature_button_text', 'Button Text'),
                Field::make('text', $prefix . 'feature_button_url', 'Button URL'),
                Field::make('radio', $prefix . 'feature_image_type', 'Image Type')
                    ->add_options([
                        'single' => 'Single Image',
                        'carousel' => 'Carousel'
                    ]),
                Field::make('image', $prefix . 'feature_image', 'Image'),
                Field::make('media_gallery', $prefix . 'feature_carousel_images', 'Carousel')
            ];
        }
    }

Container Definition:

    <?php

    namespace App\Containers\FrontPage;

    use Carbon_Fields\Container;
    use App\Fields\FeaturedPanel;
    use App\Fields\PanelMenu;
    use App\Fields\FullWidthPanel;

    function condition()
    {
        return function ($condition) {
            $condition->where('post_id', '=', get_option('page_on_front'));
        };
    }

    add_action('carbon_fields_register_fields', function () {
        Container::make('post_meta', 'Featured Panel')
            ->where(condition())
            ->add_fields(FeaturedPanel::getFields('feature_panel_1_'));
        Container::make('post_meta', 'Panel Menu')
            ->where(condition())
            ->add_fields(PanelMenu::getFields());
        Container::make('post_meta', 'Featured Panel 2')
            ->where(condition())
            ->add_fields(FeaturedPanel::getFields('feature_panel_2_'));
        Container::make('post_meta', 'Full Width Panel')
            ->where(condition())
            ->add_fields(FullWidthPanel::getFields());
    }, 20);

## Steps to Reproduce the Problem

* This only occurs where I am using two instances of the same field grouping.
* This also only seems to occur then the condition is `->where('post_id', '=', get_option('page_on_front')`
* The problem doesn't occur on other pages / other conditions ie `'post_template', '=', 'views/template-lifestyle.blade.php')`
* All other fields work properly and the problematic field works just fine even on the front page if I use a `select` rather than a `radio`.

**Comment by deqngeorgiev** [comment] 2018-09-26 06:52
Hi @davejtoews,

I've tested your code and it works as expected - the values are being saved and the correct radio buttons are selected on page reload after save. Can you provide, please, more details about your case and/or a repository with the code where we can reproduce the problem?

**Comment by davejtoews** [comment] 2018-09-26 15:55
Thanks @deqngeorgiev. You've been given read access to https://github.com/evanshunt/brookfield-artesia. I'm using select fields in `master` but have created a `radio-debug` branch where this problem should be reproducible.

It's a project using Bedrock and Sage from [Roots.io](https://roots.io) and includes a Docker container. In theory it should start up in 3 steps:

1. create `.env` file
2. run `composer install` from project root
3. run `docker-compose -up`

Running `npm install` and `npm run build` from either the project root or the theme directory are required for front-end assets, but you shouldn't need that for this.

But depending on your setup you may just wish to copy the theme from `/src/app/themes/artesia/` and run `composer install` from the theme directory.

There's a DB included for the docker container, I've added the WP credentials to the README. 

If not using the Docker DB, you'll just need to Activate the theme and set the homepage to a static page. That static front page is where the issue occurs.

**Comment by ChrissiQ** [comment] 2018-11-07 23:06
I'm also encountering this bug.  The radio value is saved to the database properly, and is retrieved properly through the `carbon_get_post_meta` function, but after saving the page in wp-admin, after the panel has reloaded, no value is selected in the radio button (all radio options are unchecked).

Other fields save and load properly.  It's only the radio field having trouble.

Looks like I'll mitigate this for now by using a select instead.

Here's my field code for the radio:

```
            Field::make('radio', $prefix . 'text_image_carousel_style', 'Style')
                ->add_options([
                    'text_full' => 'Full height text box',
                    'text_box' => 'Text in smaller box',
                ]),
```

**Comment by davejtoews** [comment] 2018-11-08 00:00
@deqngeorgiev I see you flagged this as a bug. Were you able to reproduce? Do you still need repo access?

**Comment by vvasilev-** [comment] 2019-01-02 15:02
Closing this issue since we can't reproduce it with Carbon Fields 3.0. Feel free to reopen it if you still face the problem.

**Closed by vvasilev-** 2019-01-02 15:02 UTC
Labels: [type] bug

**Comment by KevinSupertramp** [comment] 2019-03-05 09:20
Hi there,

I have the same problem when using a radio button in a CF_Block in a complex field. The radio field is used as a conditional logic as well (not sure if related though).

- I used the same block more than once on the same page.
- Sometimes (rarely) - the radio is selected with the value on the 2nd row of the complex field. But it looks quite random.

![screen shot 2019-03-05 at 09 16 35](https://user-images.githubusercontent.com/1142786/53794305-9e159600-3f27-11e9-8b50-e38402f4f45b.png)
