### ISSUE TITLE
media gallery UI issue

### ISSUE THREAD

**Issue by sachittandukar** [htmlburger/carbon-fields#360] opened 2017-09-25 12:16 UTC
![2017-09-25_17-54-39](https://user-images.githubusercontent.com/3368938/30807774-fbb48bbe-a21a-11e7-91c3-00e91534629e.jpg)
It is a random issue in the media gallery field, in which each image takes full horizontal space. However, resizing and maximizing browser brings back all images in a row. I have tested only in Chrome version 61.0.3163.100
![2017-09-25_17-59-29](https://user-images.githubusercontent.com/3368938/30807856-53320c22-a21b-11e7-8e96-f4cc829e2646.jpg)

**Comment by jorostoyanov** [comment] 2017-09-25 13:19
Hi @sachittandukar 

I have tested the field on both PC and Mac devices, however, I wasn't able to reproduce it.

Can you try disabling all active plugins and test the field again?

**Comment by atanas-angelov-dev** [comment] 2017-10-02 07:36
Closing this ticket due to lack of communication.
Feel free to reopen it with the details @jorostoyanov requested.

**Closed by atanas-angelov-dev** 2017-10-02 07:36 UTC
Labels: question

**Comment by zevilz** [comment] 2017-10-08 16:02
Same issue on Firefox 53/57 and Crome 61.0.3163.100
![08-10-2017 20-42-26](https://user-images.githubusercontent.com/12094229/31318434-0c65ecc2-ac6c-11e7-84d6-5bedc6940343.png)

**Comment by zevilz** [comment] 2017-10-08 16:20
![08-10-2017 21-18-55](https://user-images.githubusercontent.com/12094229/31318594-54469ef4-ac6e-11e7-972b-968a4d8b09f0.png)

**Comment by zevilz** [comment] 2017-10-09 14:26
Issue isn't present in MacOS (Safari v. 11.0, Chrome v. 60.0.3112.90)

**Comment by sachittandukar** [comment] 2017-10-25 16:23
Hi @atanas-angelov-dev ,

I apologize for late reply. I left the company with whom I was working on it. So, I couldn't access project/code to debug it.

However, in my case, gallery was in tabs as mentioned by @zevilz 

Thanks!

**Comment by jorostoyanov** [comment] 2017-10-30 10:38
@zevilz, @sachittandukar ,

FYI, the discussion has been moved to #389

Thanks for the reports!
