### ISSUE TITLE
Text fields get prepopulated

### ISSUE THREAD

**Issue by Geckoff** [htmlburger/carbon-fields#473] opened 2018-03-04 01:34 UTC
## Version

  - Carbon Fields: 2.1
  - WordPress: 4.9.4
  - PHP: 5.6.3

## Expected Behavior
Adding new posts with no issues :)

## Actual Behavior
The issue I'm coming across related to Carbon Fields text fields. I am using Carbon Fields with a custom post type. Also, I am using 'save_post' hook for this post type and retrieving Carbon Fields values with carbon_get_post_meta() in the function attached to the hook. When I'm trying to create a new post of my custom post type, I am getting text fields populated with the values from the first post published. This prepopulation occurs only for the fields I am using carbon_get_post_meta() for. 

## Container definition
```php
Container::make( 'post_meta', __( 'General Info', 'crb' ) )
	->where( 'post_type', '=', 'jsdisplay' )
	->add_fields( array(
		Field::make( 'text', 'jsdid', 'ID' )
			->set_attribute( 'pattern', '[a-z]+[a-z0-9-_]*[a-z0-9]+' )
			->set_required( true )
			->set_help_text('May contain only lowercase letters, numbers, "-" and "_" characters and should start with a letter and end with a letter or a number.'),
		Field::make( 'select', 'jsd_css_display', 'CSS display type' )
			->add_options( array(
				'block' => 'Block',
				'inline' => 'Inline',
				'inline-block' => 'Inline Block',
				'flex' => 'Flex',
			) )
			->set_help_text('Used for JS display functionality.')
	) );
```

## Comments
Was able to overcome this issue by using native Wordpress get_post_meta function instead of carbon_get_post_meta.

**Comment by atanas-angelov-dev** [comment] 2018-03-04 07:39
Hi @Geckoff ,

I believe this issue was addressed in one of the 2.2 beta releases. Kindly test with the latest beta release and let us know if the issue is resolved.

**Comment by Geckoff** [comment] 2018-03-04 17:48
Sorry, apparently I specified the wrong version. I am using one that is on master branch now.  As far as I understand it's 2.2.0-beta.5.

**Comment by deqngeorgiev** [comment] 2018-04-04 07:01
Hi @Geckoff ,

Unfortunately, I can't reproduce your issue (version 2.2.0) so can you provide more information about your use case?

**Comment by jorostoyanov** [comment] 2018-10-30 10:09
Closing due to inactivity.

@Geckoff feel free to open a new issue if you experience the problem again.

**Closed by jorostoyanov** 2018-10-30 10:09 UTC
Labels: question
