### ISSUE TITLE
Image field with set_value_type('url')

### ISSUE THREAD

**Issue by MDSilviu** [htmlburger/carbon-fields#620] opened 2018-12-19 21:07 UTC
## Version

Carbon Fields: 3.0.0-rc.3

Image field with set_value_type('url') doesn't display the thumbnail after save
![set-url](https://user-images.githubusercontent.com/5260249/50248170-c68afb00-03e2-11e9-887e-84c034457c49.png)

**Comment by vvasilev-** [comment] 2018-12-20 09:13
Hi @MDSilviu,

Just to confirm that we're on the same page - You've created an `Image` field and saved the page and then you add `set_value_type('url')` to the definition and the thumb is no longer displayed?

In that case, I think this is intended because you changed the type of the value that is saved in the database and we no longer can't get the metadata of the attachment used to display the thumbnail.
For 3.0, this behavior will remain as is, but in the next versions, we'll revisit it.

I'm closing this issue for now but if you have any questions feel free to ping me. :)

**Comment by vvasilev-** [comment] 2018-12-20 09:36
Okay, we'll check it.

**Comment by jorostoyanov** [comment] 2018-12-20 10:09
Hi @MDSilviu ,

I have tested the following definition in both v2.2 and v3.

```
Container::make( 'theme_options', __( 'Theme Options' ) )
	->set_page_file( 'crbn-theme-options.php' ) 
	->add_fields( array(
		Field::make( 'image', 'image' )
			->set_value_type( 'url' )
	) );
```

And in both versions the preview is being displayed as expected.

However, if you've added `->set_value_type( 'url' )` after selecting an image, in both versions the preview is not displayed which is expected behavior.

Hope that makes sense.

**Closed by jorostoyanov** 2018-12-20 10:09 UTC
Labels: bug
